server:
  port: 8701 # 服务消费方

# 指定当前eureka客户端的注册地址,
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8700/eureka
  instance:
    hostname: localhost

#当前服务名称
spring:
  application:
    name: eureka-consumer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1214678844
    url: jdbc:mysql://localhost:3306/dbd?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    type: com.zaxxer.hikari.HikariDataSource